# .streamlit/secrets.toml
DB_URL = "postgresql://neondb_owner:npg_NoHxc94RdzyX@ep-delicate-rain-ainpomwt-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
SUPABASE_URL = "https://orhfpfzgkfzdrxtgxavd.supabase.co"
SUPABASE_KEY = "sb_publishable_seSXNeJMPuF-KRP6oxVIaw_19VKrqmmsb_secret_xVPZAiRku77mbEgEsUEbYw_72kFkpgO"